<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="2122" started-at="2021-02-16T15:46:15 EET" finished-at="2021-02-16T15:46:17 EET">
    <groups>
    </groups>
    <test name="Default test" duration-ms="2122" started-at="2021-02-16T15:46:15 EET" finished-at="2021-02-16T15:46:17 EET">
      <class name="call.center.Testbase$TestBase">
        <test-method status="PASS" signature="startdriver()[pri:0, instance:call.center.Testbase$TestBase@30e9ca13]" name="startdriver" is-config="true" duration-ms="12344" started-at="2021-02-16T15:46:03 EET" finished-at="2021-02-16T15:46:15 EET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startdriver -->
      </class> <!-- call.center.Testbase$TestBase -->
      <class name="call.center.logintest">
        <test-method status="FAIL" signature="loginuser()[pri:1, instance:call.center.logintest@46185a1b]" name="loginuser" duration-ms="2050" started-at="2021-02-16T15:46:15 EET" finished-at="2021-02-16T15:46:17 EET">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:70)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:39)
at com.sun.proxy.$Proxy8.sendKeys(Unknown Source)
at call.center.Pagebase.settxtelmenttxt(Pagebase.java:25)
at call.center.loginpage.loginform(loginpage.java:26)
at call.center.logintest.loginuser(logintest.java:14)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginuser -->
      </class> <!-- call.center.logintest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
